"""Detect mistyped iNaturalist observation IDs and suggest corrections.

A specimen whose observation is missing, or whose community ID is a plant,
insect, or fish, almost certainly has a digit typo in its iNat number (after
Alan Rockefeller's approach). Candidates are generated by single digit edits
of the observation ID, fetched from the observations API, filtered to
fungal-plausible kingdoms, and ranked by whether the candidate's observer
has other specimens in this run, whether its taxon agrees with the
specimen's sequence, and how likely the edit type is as a typo.

The suggested mapping is written to the summarize output directory so it
can be reviewed and patched before upload to MycoMap.
"""

import json
import logging
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

from .inat import API_URL, MAX_BATCH_SIZE, apply_corrections, extract_inat_ids
from .util import USER_AGENT

logger = logging.getLogger(__name__)

# Iconic taxa that are plausible foray targets: fungi, and slime molds
# (iNat files Myxomycetes under Protozoa). An empty iconic taxon means the
# observation simply has no community ID yet — not a bad target.
ALLOWED_ICONIC = {"Fungi", "Protozoa", ""}

SUGGESTIONS_FILENAME = "inat_id_suggestions.tsv"
CORRECTIONS_FILENAME = "inat_id_corrections.tsv"

# Edit-type plausibility as a typo, highest first: swapped neighbours are
# the classic transcription error; dropped/doubled digits change the ID's
# length and are rarer.
_EDIT_RANK = {"transposition": 3, "substitution": 2, "deletion": 1, "insertion": 1}


def digit_edit_candidates(obs_id: str) -> dict[str, str]:
    """All observation IDs one digit-edit away: {candidate: edit_type}.

    Excludes the original and anything with a leading zero. When a candidate
    is reachable by several edit types, the most typo-plausible one wins.
    """
    candidates: dict[str, str] = {}

    def add(cand: str, edit: str):
        if cand == obs_id or not cand or cand[0] == "0":
            return
        if cand not in candidates or _EDIT_RANK[edit] > _EDIT_RANK[candidates[cand]]:
            candidates[cand] = edit

    n = len(obs_id)
    for i in range(n - 1):  # adjacent transpositions
        add(obs_id[:i] + obs_id[i + 1] + obs_id[i] + obs_id[i + 2:], "transposition")
    for i in range(n):  # substitutions
        for d in "0123456789":
            add(obs_id[:i] + d + obs_id[i + 1:], "substitution")
    for i in range(n):  # deletions
        add(obs_id[:i] + obs_id[i + 1:], "deletion")
    for i in range(n + 1):  # insertions
        for d in "0123456789":
            add(obs_id[:i] + d + obs_id[i:], "insertion")
    return candidates


def find_suspects(inat_ids: dict[str, str], specimens_info: dict[str, dict]) -> list[dict]:
    """Specimens whose observation looks mistyped.

    specimens_info[specimen_id] = {"found": bool, "iconic": str} — found is
    whether the observations API returned this ID at all. If most of the
    run's observations are unfound the fetch itself failed (offline, abort),
    so not-found detection is skipped rather than flagging everything.
    """
    total = len(inat_ids)
    found = sum(1 for sid in inat_ids if (specimens_info.get(sid) or {}).get("found"))
    report_not_found = total > 0 and found / total >= 0.8
    if total and not report_not_found:
        logger.info(
            f"Skipping not-found iNat ID detection: only {found}/{total} "
            "observations resolved (fetch may have failed)")

    suspects = []
    for sid, obs_id in inat_ids.items():
        info = specimens_info.get(sid) or {}
        if not info.get("found"):
            if report_not_found:
                suspects.append({"specimen_id": sid, "obs_id": obs_id, "problem": "not_found"})
        elif info.get("iconic", "") not in ALLOWED_ICONIC:
            suspects.append({"specimen_id": sid, "obs_id": obs_id,
                             "problem": f"non_fungi:{info['iconic']}"})
    return suspects


def fetch_observations_summary(obs_ids: list[str], abort=None, progress=None) -> dict[str, dict]:
    """Batch-fetch candidate observations: {obs_id: {taxon, iconic, login, name, observed_on}}.

    IDs that don't exist simply don't come back — that absence is the filter.
    """
    result: dict[str, dict] = {}
    if progress:
        progress(0, len(obs_ids))
    for i in range(0, len(obs_ids), MAX_BATCH_SIZE):
        if abort is not None and abort.is_set():
            logger.info("iNaturalist candidate fetch aborted (shutdown)")
            return result
        if progress:
            progress(i, len(obs_ids))
        batch = obs_ids[i : i + MAX_BATCH_SIZE]
        url = f"{API_URL}?per_page={MAX_BATCH_SIZE}&id={','.join(batch)}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read())
            for obs in data.get("results", []):
                taxon = obs.get("taxon") or {}
                user = obs.get("user") or {}
                result[str(obs["id"])] = {
                    "taxon": taxon.get("name") or "",
                    "iconic": taxon.get("iconic_taxon_name") or "",
                    "login": user.get("login") or "",
                    "name": user.get("name") or "",
                    "observed_on": obs.get("observed_on") or "",
                }
        except (urllib.error.URLError, OSError, json.JSONDecodeError, KeyError) as e:
            logger.warning(f"Failed to fetch iNaturalist candidate batch: {e}")
        if progress:
            progress(min(i + MAX_BATCH_SIZE, len(obs_ids)), len(obs_ids))
        if i + MAX_BATCH_SIZE < len(obs_ids):
            time.sleep(1)
    return result


def rank_suggestions(
    candidates: dict[str, str],
    fetched: dict[str, dict],
    run_observers: set[str],
    hit_genera: set[str],
) -> list[dict]:
    """Rank existing, fungal-plausible candidates for one suspect.

    Sort key, strongest first: candidate's observer has other specimens in
    this run; candidate's taxon genus matches the specimen's sequence; then
    edit-type plausibility.
    """
    ranked = []
    for obs_id, edit in candidates.items():
        info = fetched.get(obs_id)
        if not info:
            continue
        if info["iconic"] not in ("Fungi", "Protozoa"):
            continue
        observer_in_run = info["login"].lower() in run_observers
        genus = info["taxon"].split()[0].lower() if info["taxon"] else ""
        seq_match = bool(genus) and genus in hit_genera
        ranked.append({
            "obs_id": obs_id, "edit": edit,
            "observer_in_run": observer_in_run, "seq_match": seq_match,
            **info,
        })
    ranked.sort(key=lambda r: (r["observer_in_run"], r["seq_match"], _EDIT_RANK[r["edit"]]),
                reverse=True)
    return ranked


def _evidence(r: dict) -> str:
    parts = [r["edit"]]
    if r["observer_in_run"]:
        parts.append("observer_in_run")
    if r["seq_match"]:
        parts.append("sequence_genus_match")
    return ",".join(parts)


def check_inat_ids(
    inat_ids: dict[str, str],
    specimens_info: dict[str, dict],
    run_observers: set[str],
    hit_genera_by_specimen: dict[str, set[str]],
    out_dir: Path,
    statuses: dict[str, str] | None = None,
    abort=None,
    progress=None,
) -> list[dict]:
    """Find suspect iNat IDs, rank corrections, and write the mapping TSV.

    Returns the written records. The TSV always includes every suspect —
    with an empty suggestion when no plausible candidate exists — so the
    operator sees the full review list before upload. `statuses` marks
    specimens the admin already handled (accepted/dismissed).
    """
    suspects = find_suspects(inat_ids, specimens_info)
    if not suspects:
        return []
    logger.info(f"Checking {len(suspects)} suspect iNaturalist IDs for typos")

    all_candidates = {s["specimen_id"]: digit_edit_candidates(s["obs_id"]) for s in suspects}
    unique_ids = sorted({cid for cands in all_candidates.values() for cid in cands})
    fetched = fetch_observations_summary(unique_ids, abort=abort, progress=progress)

    records = []
    for s in suspects:
        ranked = rank_suggestions(
            all_candidates[s["specimen_id"]], fetched, run_observers,
            hit_genera_by_specimen.get(s["specimen_id"], set()),
        )
        top = ranked[0] if ranked else None
        records.append({
            **s,
            "suggested_obs_id": top["obs_id"] if top else "",
            "suggested_taxon": top["taxon"] if top else "",
            "suggested_observer": (top["name"] or top["login"]) if top else "",
            "evidence": _evidence(top) if top else "",
            "alternates": ";".join(
                f"{r['obs_id']}({r['taxon'] or 'unnamed'},{r['login']})"
                for r in ranked[1:4]),
            "status": (statuses or {}).get(s["specimen_id"], "pending"),
        })

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / SUGGESTIONS_FILENAME
    cols = ["specimen_id", "obs_id", "problem", "suggested_obs_id",
            "suggested_taxon", "suggested_observer", "evidence", "alternates",
            "status"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\t".join(cols) + "\n")
        for r in records:
            f.write("\t".join(str(r[c]) for c in cols) + "\n")
    suggested = sum(1 for r in records if r["suggested_obs_id"])
    logger.info(f"Wrote {len(records)} iNat ID suspects "
                f"({suggested} with suggestions) to {path}")
    return records


def write_corrections_tsv(corrections: dict[str, dict], out_dir: Path) -> Path | None:
    """Write the accepted mapping — the patch to apply before upload.

    corrections: {specimen_id: {"old": obs_id, "new": obs_id}}.
    """
    if not corrections:
        return None
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / CORRECTIONS_FILENAME
    with open(path, "w", encoding="utf-8") as f:
        f.write("specimen_id\told_obs_id\tnew_obs_id\n")
        for sid in sorted(corrections):
            c = corrections[sid]
            f.write(f"{sid}\t{c.get('old', '')}\t{c['new']}\n")
    logger.info(f"Wrote {len(corrections)} accepted iNat ID corrections to {path}")
    return path


# One check at a time, whichever thread asks (pipeline round, taxa-fetch
# follow-up, or an admin rescan) — the work is identical and idempotent.
_check_running = threading.Lock()


def run_inat_check(state, event_log, out_dir: Path, abort=None, progress=None) -> bool:
    """Audit the run's iNat IDs from live state and publish the results.

    Builds inputs from PipelineState, writes the suggestions TSV, emits the
    inat.suggestions event, and refreshes the corrections TSV. Returns False
    if a check was already running (the caller can just not care).
    """
    if not _check_running.acquire(blocking=False):
        logger.info("iNat ID check already running; skipping")
        return False
    try:
        inat_ids = apply_corrections(
            extract_inat_ids([{"specimen_id": sid} for sid in state.specimens]),
            state.inat_corrections,
        )
        if not inat_ids:
            return True
        specimens_info = {}
        run_observers = set()
        hit_genera = {}
        for sid, spec in state.specimens.items():
            # Every real observation has an observer, so a missing login
            # means the observations API never returned this ID.
            login = (spec.inat_observer or {}).get("login", "")
            if login:
                run_observers.add(login.lower())
            specimens_info[sid] = {
                "found": bool(login),
                "iconic": spec.community_iconic_taxon,
            }
            genera = set()
            for m in spec.identification:
                if m.top_hits:
                    name = (m.top_hits[0].get("name") or m.top_hits[0].get("ref_id") or "")
                    if name.strip():
                        genera.add(name.split()[0].lower())
            if genera:
                hit_genera[sid] = genera

        statuses = {sid: "accepted" for sid in state.inat_corrections}
        statuses.update({sid: "dismissed" for sid in state.inat_dismissed})
        records = check_inat_ids(
            inat_ids, specimens_info, run_observers, hit_genera,
            out_dir, statuses=statuses, abort=abort, progress=progress,
        )
        event_log.emit("inat.suggestions", {"suggestions": records})
        write_corrections_tsv(state.inat_corrections, out_dir)
        return True
    finally:
        _check_running.release()
